version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "welcome-to-costco-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-y2dby7c1jeat"
s3_prefix = "welcome-to-costco-test"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
